
name = "DashQueryBuilder"
uuid = "1b08a953-4be3-4667-9a23-9717610fdc70"
authors = ["Tyler Baur <baur.tyler@protonmail.com>"]
version = "0.2.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
